site_name: Appunti universitari
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        #icon: material/toggle-switch-off-outline
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: green
      language: it
      media: "(prefers-color-scheme: light)"
    - scheme: slate # 
      toggle:
        #icon: material/toggle-switch
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: green
      language: it
      media: "(prefers-color-scheme: dark)"
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navitation.sections
    #- navigation.expand
    - navigation.indexes
    - search.highlight
    - content.tabs.link
    - content.code.annotate

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - tables
  - meta
  - def_list

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: Indice
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      #custom_checkbox: true
  - pymdownx.tilde


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/biggerAdmonitions.css
  - stylesheets/mathAdmonitions.css

plugins:
  - search:
      lang: it


# Page tree
nav:
  - Programmazione e Algoritmica:
    - Introduzione: ProAlgo/introduzione.md
    - Grammatiche e Linguaggi: ProAlgo/grammatiche.md 
    - Sintassi: ProAlgo/sintassi.md
    - Semantica: ProAlgo/semantica.md
    - Valutazione di un algoritmo: ProAlgo/valutazione.md
    - Linguaggio L: ProAlgo/l.md
    - Programmazione dinamica: ProAlgo/programmazioneDinamica.md
  - Fondamenti di Informatica:
    #- Introduzione: FdI/index.md
    - Insiemi: FdI/insiemi.md
    - Relazioni: FdI/relazioni.md
    - Induzione Matematica: FdI/induzione.md
    - Relazioni su insiemi: FdI/relazioniInsiemi.md
    - Grafi: FdI/grafi.md
    - Calcolo Combinatorio: FdI/calcoloCombinatorio.md
    - Induzione Strutturale e Ricorsione: FdI/induzioneRicorsione.md
    - Linguaggi Formali: FdI/linguaggi.md
    - Logica Matematica: FdI/logica.md
    - Cheatsheet: FdI/cheatsheet.md
  - Laboratorio I: LabI/index.md
  - Analisi I: 
    - Funzioni ed introduzione: AnalisiI/prerequisiti.md
    - Calcolo differenziale: AnalisiI/calcoloDifferenziale.md
    - Limiti: AnalisiI/limiti.md
  - Algebra Lineare: AlgebraLineare/index.md

